### ISSUE TITLE
Little bit confused on how to use this

### ISSUE THREAD

**Issue by paulosllvn** [ionic-team/ionic-e2e-example#6]
How do I actually use this in relation to an ionic capacitor app? Is there a tutorial on how to use it and write some practice tests? I tried to clone this and run it but was given an error 

```
'TS_NODE_PROJECT' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-conference-app@0.0.0 ionic-e2e:run:android: `TS_NODE_PROJECT=tests/tsconfig.json  wdio tests/config/wdio.android.config.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-conference-app@0.0.0 ionic-e2e:run:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mlynch** [comment]
Are you on Windows?

**Comment by paulosllvn** [comment]
> 

Yes i am using windows

**Comment by nive745** [comment]
@paulosllvn Are you able to run test cases with appium

**Comment by achacofe** [comment]
Good, In my case I am using Mac, macOS Monterey, with version 12.3.

When executing any test command, I get the same error on the console
npm run ionic-e2e:run:ios

```
npm ERR! ionic-conference-app@0.0.0 ionic-e2e:run:ios: `TS_NODE_PROJECT=tests/tsconfig.json  wdio tests/config/wdio.ios.config.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-conference-app@0.0.0 ionic-e2e:run:ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/achacofe/.npm/_logs/2022-03-30T07_52_41_976Z-debug.log
```

But when executing any test command, I get the same error on the console:
npm run ionic-e2e:run:web

```
> ionic-conference-app@0.0.0 ionic-e2e:run:web /Users/achacofe/pocs/Ionic-FWKA6369/ionic-e2e-example
> TS_NODE_PROJECT=tests/tsconfig.json  wdio tests/config/wdio.web.config.ts

[0-0] RUNNING in chrome - /tests/specs/app.about.spec.ts, /tests/specs/app.account.spec.ts, /tests/specs/app.login.spec.ts, /tests/specs/app.map.spec.ts, /tests/specs/app.schedule-filter.spec.ts, /tests/specs/app.schedule.spec.ts, /tests/specs/app.session-detail.spec.ts, /tests/specs/app.signup.spec.ts, /tests/specs/app.speaker-detail.spec.ts, /tests/specs/app.speaker-list.spec.ts, /tests/specs/app.support.spec.ts, /tests/specs/app.tutorial.spec.ts
ERROR webdriver: Request failed with status 500 due to session not created: session not created: This version of ChromeDriver only supports Chrome version 96
[0-0] Current browser version is 100.0.4896.60 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[0-0]  ERROR webdriver: 0   chromedriver                        0x000000010a636269 __gxx_personality_v0 + 582729
[0-0] 1   chromedriver                        0x000000010a5c1c33 __gxx_personality_v0 + 106003
[0-0] 2   chromedriver                        0x000000010a17ee28 chromedriver + 171560
[0-0] 3   chromedriver                        0x000000010a1a5433 chromedriver + 328755
[0-0] 4   chromedriver                        0x000000010a1a0ff6 chromedriver + 311286
[0-0] 5   chromedriver                        0x000000010a19d6c6 chromedriver + 296646
[0-0] 6   chromedriver                        0x000000010a1d79c3 chromedriver + 534979
[0-0] 7   chromedriver                        0x000000010a1d1723 chromedriver + 509731
[0-0] 8   chromedriver                        0x000000010a1a775e chromedriver + 337758
[0-0] 9   chromedriver                        0x000000010a1a8a95 chromedriver + 342677
[0-0] 10  chromedriver                        0x000000010a5f28ab __gxx_personality_v0 + 305803
[0-0] 11  chromedriver                        0x000000010a609863 __gxx_personality_v0 + 399939
[0-0] 12  chromedriver                        0x000000010a60ec7f __gxx_personality_v0 + 421471
[0-0] 13  chromedriver                        0x000000010a60abba __gxx_personality_v0 + 404890
[0-0] 14  chromedriver                        0x000000010a5e6e51 __gxx_personality_v0 + 258097
[0-0] 15  chromedriver                        0x000000010a626158 __gxx_personality_v0 + 516920
[0-0] 16  chromedriver                        0x000000010a6262e1 __gxx_personality_v0 + 517313
[0-0] 17  chromedriver                        0x000000010a63d6f8 __gxx_personality_v0 + 612568
[0-0] 18  libsystem_pthread.dylib             0x00007ff8034e14e1 _pthread_start + 125
[0-0] 19  libsystem_pthread.dylib             0x00007ff8034dcf6b thread_start + 15
[0-0] 
[0-0] 2022-03-30T07:54:57.231Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] session not created: This version of ChromeDriver only supports Chrome version 96
[0-0] Current browser version is 100.0.4896.60 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[0-0]     at startWebDriverSession (/Users/achacofe/pocs/Ionic-FWKA6369/ionic-e2e-example/node_modules/webdriver/build/utils.js:72:15)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0] FAILED in chrome - /tests/specs/app.about.spec.ts, /tests/specs/app.account.spec.ts, /tests/specs/app.login.spec.ts, /tests/specs/app.map.spec.ts, /tests/specs/app.schedule-filter.spec.ts, /tests/specs/app.schedule.spec.ts, /tests/specs/app.session-detail.spec.ts, /tests/specs/app.signup.spec.ts, /tests/specs/app.speaker-detail.spec.ts, /tests/specs/app.speaker-list.spec.ts, /tests/specs/app.support.spec.ts, /tests/specs/app.tutorial.spec.ts

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:13 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-conference-app@0.0.0 ionic-e2e:run:web: `TS_NODE_PROJECT=tests/tsconfig.json  wdio tests/config/wdio.web.config.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-conference-app@0.0.0 ionic-e2e:run:web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/achacofe/.npm/_logs/2022-03-30T07_54_57_622Z-debug.log
```

NOTA: Here I do not use a capacitor because it is the project of this repo, but to carry out these tests in a project with a capacitor, how should it be used? Can you document this a bit more?

**Comment by wswebcreation** [comment]
Hi @achacofe 

Can you run the test again, but then with `VERBOSE=true npm run ionic-e2e:run:android`, see https://github.com/ionic-team/ionic-e2e-example/blob/main/tests/config/wdio.shared.appium.config.ts#L28

This would create a log for Appium and would tell us more about what happened with Appium. It should automatically download the correct ChromeDriver version (which is likely not happening according to the error). Can you share the logs as a gist?

**Comment by mannysangra** [comment]
@mlynch @paulosllvn this way will solve y problem `npx wdio run tests/config/wdio.android.config.ts --autoCompileOpts.tsNodeOpts.project=tests/tsconfig.json`
